id = "kanagawa-themes"
name = "Kanagawa Themes"
version = "0.1.2"
schema_version = 1
authors = [
    "Ethan Gilmore <ethanmckgilmore@gmail.com>",
    "Yair Chan <enyaoficial001@gmail.com",
]
description = "ðŸŒŠ Zed port of rebelot's Kanagawa.nvim theme ðŸ‰"
repository = "https://github.com/ethangilmore/zed-kanagawa"
